services:
  runner:
    image: myoung34/github-runner:latest
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - RUNNER_SCOPE=${RUNNER_SCOPE}
      - RUNNER_NAME_PREFIX=${RUNNER_NAME_PREFIX}
      - LABELS=${RUNNER_LABELS}
      - REPO_URL=${GITHUB_REPO_URL}
      - EPHEMERAL=${RUNNER_EPHEMERAL}
      - ACCESS_TOKEN=${GITHUB_ACCESS_TOKEN}
    deploy:
      replicas: ${RUNNER_REPLICAS}
      resources:
        limits:
          cpus: '${RUNNER_CPU_LIMIT}'
          memory: ${RUNNER_MEM_LIMIT}
        reservations:
          cpus: '${RUNNER_CPU_RESERVATION}'
          memory: ${RUNNER_MEM_RESERVATION}
