# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: usage/usage.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'usage/usage.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11usage/usage.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"H\n\x08UserInfo\x12\x11\n\tuser_uuid\x18\x01 \x01(\t\x12\x12\n\nuser_email\x18\x02 \x01(\t\x12\x15\n\ruser_key_name\x18\x03 \x01(\t\"\x7f\n\rInferenceInfo\x12\x12\n\nmodel_type\x18\x01 \x01(\t\x12\x16\n\x0emodel_provider\x18\x02 \x01(\t\x12\x12\n\nmodel_name\x18\x03 \x01(\t\x12\x1b\n\x13model_inferene_type\x18\x04 \x01(\t\x12\x11\n\tcall_type\x18\x05 \x01(\t\"\xa6\x03\n\tUsageInfo\x12\x33\n\rusage_details\x18\x01 \x03(\x0b\x32\x1c.UsageInfo.UsageDetailsEntry\x12\x1c\n\x14usage_details_string\x18\x02 \x01(\t\x12\r\n\x05input\x18\x03 \x01(\t\x12\x0e\n\x06output\x18\x04 \x01(\t\x12\r\n\x05level\x18\x05 \x01(\t\x12\x0f\n\x07message\x18\x06 \x01(\t\x12.\n\nstart_time\x18\x07 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12,\n\x08\x65nd_time\x18\x08 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12*\n\x08metadata\x18\t \x03(\x0b\x32\x18.UsageInfo.MetadataEntry\x12\x17\n\x0f\x61\x64\x64itional_info\x18\n \x01(\t\x1a\x33\n\x11UsageDetailsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x04:\x02\x38\x01\x1a/\n\rMetadataEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"z\n\x12\x43reateUsageRequest\x12\x1c\n\tuser_info\x18\x01 \x01(\x0b\x32\t.UserInfo\x12&\n\x0einference_info\x18\x02 \x01(\x0b\x32\x0e.InferenceInfo\x12\x1e\n\nusage_info\x18\x03 \x01(\x0b\x32\n.UsageInfo\"5\n\x13\x43reateUsageResponse\x12\r\n\x05\x65rror\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t2A\n\x05Usage\x12\x38\n\tSaveUsage\x12\x13.CreateUsageRequest\x1a\x14.CreateUsageResponse\"\x00\x42)Z\'github.com/longlnOff/usages-proto/usageb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'usage.usage_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\'github.com/longlnOff/usages-proto/usage'
  _globals['_USAGEINFO_USAGEDETAILSENTRY']._loaded_options = None
  _globals['_USAGEINFO_USAGEDETAILSENTRY']._serialized_options = b'8\001'
  _globals['_USAGEINFO_METADATAENTRY']._loaded_options = None
  _globals['_USAGEINFO_METADATAENTRY']._serialized_options = b'8\001'
  _globals['_USERINFO']._serialized_start=54
  _globals['_USERINFO']._serialized_end=126
  _globals['_INFERENCEINFO']._serialized_start=128
  _globals['_INFERENCEINFO']._serialized_end=255
  _globals['_USAGEINFO']._serialized_start=258
  _globals['_USAGEINFO']._serialized_end=680
  _globals['_USAGEINFO_USAGEDETAILSENTRY']._serialized_start=580
  _globals['_USAGEINFO_USAGEDETAILSENTRY']._serialized_end=631
  _globals['_USAGEINFO_METADATAENTRY']._serialized_start=633
  _globals['_USAGEINFO_METADATAENTRY']._serialized_end=680
  _globals['_CREATEUSAGEREQUEST']._serialized_start=682
  _globals['_CREATEUSAGEREQUEST']._serialized_end=804
  _globals['_CREATEUSAGERESPONSE']._serialized_start=806
  _globals['_CREATEUSAGERESPONSE']._serialized_end=859
  _globals['_USAGE']._serialized_start=861
  _globals['_USAGE']._serialized_end=926
# @@protoc_insertion_point(module_scope)
