// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.12.4
// source: usage/usage.proto

package usage

import (
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UserInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserUuid      string                 `protobuf:"bytes,1,opt,name=user_uuid,json=userUuid,proto3" json:"user_uuid,omitempty"`
	UserEmail     string                 `protobuf:"bytes,2,opt,name=user_email,json=userEmail,proto3" json:"user_email,omitempty"`
	UserKeyName   string                 `protobuf:"bytes,3,opt,name=user_key_name,json=userKeyName,proto3" json:"user_key_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserInfo) Reset() {
	*x = UserInfo{}
	mi := &file_usage_usage_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserInfo) ProtoMessage() {}

func (x *UserInfo) ProtoReflect() protoreflect.Message {
	mi := &file_usage_usage_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserInfo.ProtoReflect.Descriptor instead.
func (*UserInfo) Descriptor() ([]byte, []int) {
	return file_usage_usage_proto_rawDescGZIP(), []int{0}
}

func (x *UserInfo) GetUserUuid() string {
	if x != nil {
		return x.UserUuid
	}
	return ""
}

func (x *UserInfo) GetUserEmail() string {
	if x != nil {
		return x.UserEmail
	}
	return ""
}

func (x *UserInfo) GetUserKeyName() string {
	if x != nil {
		return x.UserKeyName
	}
	return ""
}

type InferenceInfo struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	ModelType         string                 `protobuf:"bytes,1,opt,name=model_type,json=modelType,proto3" json:"model_type,omitempty"`
	ModelProvider     string                 `protobuf:"bytes,2,opt,name=model_provider,json=modelProvider,proto3" json:"model_provider,omitempty"`
	ModelName         string                 `protobuf:"bytes,3,opt,name=model_name,json=modelName,proto3" json:"model_name,omitempty"`
	ModelInfereneType string                 `protobuf:"bytes,4,opt,name=model_inferene_type,json=modelInfereneType,proto3" json:"model_inferene_type,omitempty"`
	CallType          string                 `protobuf:"bytes,5,opt,name=call_type,json=callType,proto3" json:"call_type,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *InferenceInfo) Reset() {
	*x = InferenceInfo{}
	mi := &file_usage_usage_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InferenceInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InferenceInfo) ProtoMessage() {}

func (x *InferenceInfo) ProtoReflect() protoreflect.Message {
	mi := &file_usage_usage_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InferenceInfo.ProtoReflect.Descriptor instead.
func (*InferenceInfo) Descriptor() ([]byte, []int) {
	return file_usage_usage_proto_rawDescGZIP(), []int{1}
}

func (x *InferenceInfo) GetModelType() string {
	if x != nil {
		return x.ModelType
	}
	return ""
}

func (x *InferenceInfo) GetModelProvider() string {
	if x != nil {
		return x.ModelProvider
	}
	return ""
}

func (x *InferenceInfo) GetModelName() string {
	if x != nil {
		return x.ModelName
	}
	return ""
}

func (x *InferenceInfo) GetModelInfereneType() string {
	if x != nil {
		return x.ModelInfereneType
	}
	return ""
}

func (x *InferenceInfo) GetCallType() string {
	if x != nil {
		return x.CallType
	}
	return ""
}

type UsageInfo struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	UsageDetails       map[string]float32     `protobuf:"bytes,1,rep,name=usage_details,json=usageDetails,proto3" json:"usage_details,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"fixed32,2,opt,name=value"`
	UsageDetailsString string                 `protobuf:"bytes,2,opt,name=usage_details_string,json=usageDetailsString,proto3" json:"usage_details_string,omitempty"`
	Input              string                 `protobuf:"bytes,3,opt,name=input,proto3" json:"input,omitempty"`
	Output             string                 `protobuf:"bytes,4,opt,name=output,proto3" json:"output,omitempty"`
	Level              string                 `protobuf:"bytes,5,opt,name=level,proto3" json:"level,omitempty"`
	Message            string                 `protobuf:"bytes,6,opt,name=message,proto3" json:"message,omitempty"`
	StartTime          *timestamp.Timestamp   `protobuf:"bytes,7,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	EndTime            *timestamp.Timestamp   `protobuf:"bytes,8,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	Metadata           map[string]string      `protobuf:"bytes,9,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	AdditionalInfo     string                 `protobuf:"bytes,10,opt,name=additional_info,json=additionalInfo,proto3" json:"additional_info,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *UsageInfo) Reset() {
	*x = UsageInfo{}
	mi := &file_usage_usage_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UsageInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UsageInfo) ProtoMessage() {}

func (x *UsageInfo) ProtoReflect() protoreflect.Message {
	mi := &file_usage_usage_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UsageInfo.ProtoReflect.Descriptor instead.
func (*UsageInfo) Descriptor() ([]byte, []int) {
	return file_usage_usage_proto_rawDescGZIP(), []int{2}
}

func (x *UsageInfo) GetUsageDetails() map[string]float32 {
	if x != nil {
		return x.UsageDetails
	}
	return nil
}

func (x *UsageInfo) GetUsageDetailsString() string {
	if x != nil {
		return x.UsageDetailsString
	}
	return ""
}

func (x *UsageInfo) GetInput() string {
	if x != nil {
		return x.Input
	}
	return ""
}

func (x *UsageInfo) GetOutput() string {
	if x != nil {
		return x.Output
	}
	return ""
}

func (x *UsageInfo) GetLevel() string {
	if x != nil {
		return x.Level
	}
	return ""
}

func (x *UsageInfo) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *UsageInfo) GetStartTime() *timestamp.Timestamp {
	if x != nil {
		return x.StartTime
	}
	return nil
}

func (x *UsageInfo) GetEndTime() *timestamp.Timestamp {
	if x != nil {
		return x.EndTime
	}
	return nil
}

func (x *UsageInfo) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *UsageInfo) GetAdditionalInfo() string {
	if x != nil {
		return x.AdditionalInfo
	}
	return ""
}

type CreateUsageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserInfo      *UserInfo              `protobuf:"bytes,1,opt,name=user_info,json=userInfo,proto3" json:"user_info,omitempty"`
	InferenceInfo *InferenceInfo         `protobuf:"bytes,2,opt,name=inference_info,json=inferenceInfo,proto3" json:"inference_info,omitempty"`
	UsageInfo     *UsageInfo             `protobuf:"bytes,3,opt,name=usage_info,json=usageInfo,proto3" json:"usage_info,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateUsageRequest) Reset() {
	*x = CreateUsageRequest{}
	mi := &file_usage_usage_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateUsageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateUsageRequest) ProtoMessage() {}

func (x *CreateUsageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_usage_usage_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateUsageRequest.ProtoReflect.Descriptor instead.
func (*CreateUsageRequest) Descriptor() ([]byte, []int) {
	return file_usage_usage_proto_rawDescGZIP(), []int{3}
}

func (x *CreateUsageRequest) GetUserInfo() *UserInfo {
	if x != nil {
		return x.UserInfo
	}
	return nil
}

func (x *CreateUsageRequest) GetInferenceInfo() *InferenceInfo {
	if x != nil {
		return x.InferenceInfo
	}
	return nil
}

func (x *CreateUsageRequest) GetUsageInfo() *UsageInfo {
	if x != nil {
		return x.UsageInfo
	}
	return nil
}

type CreateUsageResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Error         bool                   `protobuf:"varint,1,opt,name=error,proto3" json:"error,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateUsageResponse) Reset() {
	*x = CreateUsageResponse{}
	mi := &file_usage_usage_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateUsageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateUsageResponse) ProtoMessage() {}

func (x *CreateUsageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_usage_usage_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateUsageResponse.ProtoReflect.Descriptor instead.
func (*CreateUsageResponse) Descriptor() ([]byte, []int) {
	return file_usage_usage_proto_rawDescGZIP(), []int{4}
}

func (x *CreateUsageResponse) GetError() bool {
	if x != nil {
		return x.Error
	}
	return false
}

func (x *CreateUsageResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_usage_usage_proto protoreflect.FileDescriptor

const file_usage_usage_proto_rawDesc = "" +
	"\n" +
	"\x11usage/usage.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"j\n" +
	"\bUserInfo\x12\x1b\n" +
	"\tuser_uuid\x18\x01 \x01(\tR\buserUuid\x12\x1d\n" +
	"\n" +
	"user_email\x18\x02 \x01(\tR\tuserEmail\x12\"\n" +
	"\ruser_key_name\x18\x03 \x01(\tR\vuserKeyName\"\xc1\x01\n" +
	"\rInferenceInfo\x12\x1d\n" +
	"\n" +
	"model_type\x18\x01 \x01(\tR\tmodelType\x12%\n" +
	"\x0emodel_provider\x18\x02 \x01(\tR\rmodelProvider\x12\x1d\n" +
	"\n" +
	"model_name\x18\x03 \x01(\tR\tmodelName\x12.\n" +
	"\x13model_inferene_type\x18\x04 \x01(\tR\x11modelInfereneType\x12\x1b\n" +
	"\tcall_type\x18\x05 \x01(\tR\bcallType\"\xad\x04\n" +
	"\tUsageInfo\x12A\n" +
	"\rusage_details\x18\x01 \x03(\v2\x1c.UsageInfo.UsageDetailsEntryR\fusageDetails\x120\n" +
	"\x14usage_details_string\x18\x02 \x01(\tR\x12usageDetailsString\x12\x14\n" +
	"\x05input\x18\x03 \x01(\tR\x05input\x12\x16\n" +
	"\x06output\x18\x04 \x01(\tR\x06output\x12\x14\n" +
	"\x05level\x18\x05 \x01(\tR\x05level\x12\x18\n" +
	"\amessage\x18\x06 \x01(\tR\amessage\x129\n" +
	"\n" +
	"start_time\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tstartTime\x125\n" +
	"\bend_time\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\aendTime\x124\n" +
	"\bmetadata\x18\t \x03(\v2\x18.UsageInfo.MetadataEntryR\bmetadata\x12'\n" +
	"\x0fadditional_info\x18\n" +
	" \x01(\tR\x0eadditionalInfo\x1a?\n" +
	"\x11UsageDetailsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x02R\x05value:\x028\x01\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x9e\x01\n" +
	"\x12CreateUsageRequest\x12&\n" +
	"\tuser_info\x18\x01 \x01(\v2\t.UserInfoR\buserInfo\x125\n" +
	"\x0einference_info\x18\x02 \x01(\v2\x0e.InferenceInfoR\rinferenceInfo\x12)\n" +
	"\n" +
	"usage_info\x18\x03 \x01(\v2\n" +
	".UsageInfoR\tusageInfo\"E\n" +
	"\x13CreateUsageResponse\x12\x14\n" +
	"\x05error\x18\x01 \x01(\bR\x05error\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage2A\n" +
	"\x05Usage\x128\n" +
	"\tSaveUsage\x12\x13.CreateUsageRequest\x1a\x14.CreateUsageResponse\"\x00B)Z'github.com/longlnOff/usages-proto/usageb\x06proto3"

var (
	file_usage_usage_proto_rawDescOnce sync.Once
	file_usage_usage_proto_rawDescData []byte
)

func file_usage_usage_proto_rawDescGZIP() []byte {
	file_usage_usage_proto_rawDescOnce.Do(func() {
		file_usage_usage_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_usage_usage_proto_rawDesc), len(file_usage_usage_proto_rawDesc)))
	})
	return file_usage_usage_proto_rawDescData
}

var file_usage_usage_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_usage_usage_proto_goTypes = []any{
	(*UserInfo)(nil),            // 0: UserInfo
	(*InferenceInfo)(nil),       // 1: InferenceInfo
	(*UsageInfo)(nil),           // 2: UsageInfo
	(*CreateUsageRequest)(nil),  // 3: CreateUsageRequest
	(*CreateUsageResponse)(nil), // 4: CreateUsageResponse
	nil,                         // 5: UsageInfo.UsageDetailsEntry
	nil,                         // 6: UsageInfo.MetadataEntry
	(*timestamp.Timestamp)(nil), // 7: google.protobuf.Timestamp
}
var file_usage_usage_proto_depIdxs = []int32{
	5, // 0: UsageInfo.usage_details:type_name -> UsageInfo.UsageDetailsEntry
	7, // 1: UsageInfo.start_time:type_name -> google.protobuf.Timestamp
	7, // 2: UsageInfo.end_time:type_name -> google.protobuf.Timestamp
	6, // 3: UsageInfo.metadata:type_name -> UsageInfo.MetadataEntry
	0, // 4: CreateUsageRequest.user_info:type_name -> UserInfo
	1, // 5: CreateUsageRequest.inference_info:type_name -> InferenceInfo
	2, // 6: CreateUsageRequest.usage_info:type_name -> UsageInfo
	3, // 7: Usage.SaveUsage:input_type -> CreateUsageRequest
	4, // 8: Usage.SaveUsage:output_type -> CreateUsageResponse
	8, // [8:9] is the sub-list for method output_type
	7, // [7:8] is the sub-list for method input_type
	7, // [7:7] is the sub-list for extension type_name
	7, // [7:7] is the sub-list for extension extendee
	0, // [0:7] is the sub-list for field type_name
}

func init() { file_usage_usage_proto_init() }
func file_usage_usage_proto_init() {
	if File_usage_usage_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_usage_usage_proto_rawDesc), len(file_usage_usage_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_usage_usage_proto_goTypes,
		DependencyIndexes: file_usage_usage_proto_depIdxs,
		MessageInfos:      file_usage_usage_proto_msgTypes,
	}.Build()
	File_usage_usage_proto = out.File
	file_usage_usage_proto_goTypes = nil
	file_usage_usage_proto_depIdxs = nil
}
