name: "Protocol Buffer Go and Python Stubs Generation"
on:
  push:
    tags:
      - "v**"

# Add this permissions block
permissions:
  contents: write  # This allows the workflow to push to the repository

jobs:
  protoc:
    name: "Generate gRPC Stubs"
    runs-on: self-hosted
    strategy:
      matrix:
        service: ["usage"]

    steps:
      - name: Install Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'
          
      - name: Setup Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          
      - uses: actions/checkout@v4
      
      - name: Extract Release Version
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
        
      - name: Install Protocol Buffer Compiler
        run: |
          sudo apt-get update
          sudo apt-get install -y protobuf-compiler
          
      - name: Install Go protoc plugins
        run: |
          go install google.golang.org/protobuf/cmd/protoc-gen-go@latest
          go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@latest
          
      - name: Install Python protoc plugins
        run: |
          python -m pip install --upgrade pip
          python -m pip install grpcio-tools
          
      - name: "Generate gRPC stubs for Golang and Python"
        shell: bash
        run: |
          chmod +x "${GITHUB_WORKSPACE}/protoc.sh"
          ls -alh ${GITHUB_WORKSPACE}
          ./protoc.sh ${{ matrix.service }} ${{ env.RELEASE_VERSION }} ${{ github.actor }} ${{ github.actor }}@users.noreply.github.com
