name: "Protocol Buffer Go Stubs Generation"
on:
  push:
    tags:
      - "v**"

# Add this permissions block
permissions:
  contents: write  # This allows the workflow to push to the repository

jobs:
  protoc:
    name: "Generate"
    runs-on: self-hosted
    strategy:
      matrix:
        service: ["usage"]

    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.24
      - uses: actions/checkout@v2
      - name: Etract Release Version
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - name: "Generate for Golang"
        shell: bash
        run: |
          chmod +x "${GITHUB_WORKSPACE}/protoc.sh"
          ls -alh ${GITHUB_WORKSPACE}
          ./protoc.sh ${{ matrix.service }} ${{ env.RELEASE_VERSION }} ${{ github.actor }} ${{ github.actor }}@users.noreply.github.com
